apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phonebook-backend
  namespace: testuser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phonebook-backend
        stage: test
    spec:
      containers:
      - name: phonebook-backend
        image: kube-registry:5000/phonebook-backend:__IMG_VERSION__
        ports:
        - containerPort: 9293
      - name: phonebook-redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-backend
  namespace: testuser
  labels:
    app: phonebook-backend
    stage: test
spec:
  selector:
    app: phonebook-backend
  ports:
  - name: phonebook-backend
    port: 80
    targetPort: 9293
    protocol: TCP
